# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: &loop_hz 125

# Settings for ros_control hardware interface
ur_hardware_interface:
   joints: &robot_joints
     - ur_arm_shoulder_pan_joint
     - ur_arm_shoulder_lift_joint
     - ur_arm_elbow_joint
     - ur_arm_wrist_1_joint
     - ur_arm_wrist_2_joint
     - ur_arm_wrist_3_joint

# Publish all joint states ----------------------------------
ur_arm_joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: *loop_hz

# Publish wrench ----------------------------------
ur_arm_force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: *loop_hz

# Publish speed_scaling factor
ur_arm_speed_scaling_state_controller:
   type:         ur_controllers/SpeedScalingStateController
   publish_rate: *loop_hz

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
ur_arm_scaled_pos_joint_traj_controller:
   type: position_controllers/ScaledJointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ur_arm_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      ur_arm_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      ur_arm_elbow_joint: {trajectory: 0.2, goal: 0.1}
      ur_arm_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      ur_arm_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      ur_arm_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20

ur_arm_pos_joint_traj_controller:
   type: position_controllers/JointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ur_arm_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      ur_arm_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      ur_arm_elbow_joint: {trajectory: 0.2, goal: 0.1}
      ur_arm_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      ur_arm_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      ur_arm_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20

ur_arm_scaled_vel_joint_traj_controller:
   type: velocity_controllers/ScaledJointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ur_arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      ur_arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      ur_arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
      ur_arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      ur_arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      ur_arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   gains:
      #!!These values have not been optimized!!
      ur_arm_shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_arm_shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_arm_elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_arm_wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_arm_wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_arm_wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
   # Use a feedforward term to reduce the size of PID gains
   velocity_ff:
      ur_arm_shoulder_pan_joint: 1.0
      ur_arm_shoulder_lift_joint: 1.0
      ur_arm_elbow_joint: 1.0
      ur_arm_wrist_1_joint: 1.0
      ur_arm_wrist_2_joint: 1.0
      ur_arm_wrist_3_joint: 1.0
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20

ur_arm_vel_joint_traj_controller:
   type: velocity_controllers/JointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ur_arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      ur_arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      ur_arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
      ur_arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      ur_arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      ur_arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   gains:
      #!!These values have not been optimized!!
      ur_arm_shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_arm_shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_arm_elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_arm_wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_arm_wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_arm_wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
   # Use a feedforward term to reduce the size of PID gains
   velocity_ff:
      ur_arm_shoulder_pan_joint: 1.0
      ur_arm_shoulder_lift_joint: 1.0
      ur_arm_elbow_joint: 1.0
      ur_arm_wrist_1_joint: 1.0
      ur_arm_wrist_2_joint: 1.0
      ur_arm_wrist_3_joint: 1.0
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20

# Pass an array of joint velocities directly to the joints
ur_arm_joint_group_vel_controller:
   type: velocity_controllers/JointGroupVelocityController
   joints: *robot_joints

ur_arm_robot_status_controller:
   type: industrial_robot_status_controller/IndustrialRobotStatusController
   handle_name: industrial_robot_status_handle
   publish_rate: 10
